# Variables
@baseUrl = http://localhost:3333

###

# @name healthCheck
GET {{baseUrl}}/health

###

# @name getRooms
GET {{baseUrl}}/rooms


###
# @name createRoom
POST  {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala do React",
    "description": "Essa é uma sala é uma pergunta referente ao React."
}

###
# References
@roomId = {{createRoom.response.body.$.roomId}}


###

# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions


###
# @name createQuestion
POST  {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "O que é React?"
}


###
# @name uploadAudio
POST  {{baseUrl}}/rooms/{{roomId}}/audio
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="audio_file"; filename="react.mp3"
Content-Type: audio/mpeg

< ./audio/react.mp3
--boundary