# Variables
@baseUrl = http://localhost:3333

###

# @name healthCheck
GET {{baseUrl}}/health

###

# @name getRooms
GET {{baseUrl}}/rooms


###
# @name createRoom
POST  {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de Teste",
    "description": "Essa é uma sala de teste."
}


###

# @name getRoomQuestions
GET {{baseUrl}}/rooms/111179ed-6778-47da-3cb9-f8813aabe33b/questions